  ;; Arena keeps the first eight solids: four perimeter walls and four pad platforms.
  (func $solid_count (result i32)
    (if (result i32) (i32.eq (i32.load (i32.const 4104)) (i32.const 2))
      (then (i32.const 8)) (else (i32.load (i32.const 32780)))))
  ;; Integer swept circle versus axis-aligned polygon edges and rounded corners.
  ;; Time uses [0,65536]; 65537 means no contact. Equal times preserve solid ID.
  (func $abs (param $v i32) (result i32)
    (if (result i32) (i32.lt_s (local.get $v) (i32.const 0)) (then (i32.sub (i32.const 0) (local.get $v))) (else (local.get $v))))
  (func $min (param $a i32) (param $b i32) (result i32)
    (if (result i32) (i32.lt_s (local.get $a) (local.get $b)) (then (local.get $a)) (else (local.get $b))))
  (func $max (param $a i32) (param $b i32) (result i32)
    (if (result i32) (i32.gt_s (local.get $a) (local.get $b)) (then (local.get $a)) (else (local.get $b))))
  (func $dist2 (param $x i32) (param $y i32) (result i64)
    (i64.add (i64.mul (i64.extend_i32_s (local.get $x)) (i64.extend_i32_s (local.get $x)))
      (i64.mul (i64.extend_i32_s (local.get $y)) (i64.extend_i32_s (local.get $y)))))
  (func $circle_dist (param $x i32) (param $y i32) (param $dx i32) (param $dy i32) (param $t i32) (result i64)
    (call $dist2 (i32.add (local.get $x) (call $mul (local.get $dx) (local.get $t)))
      (i32.add (local.get $y) (call $mul (local.get $dy) (local.get $t)))))
  (func $circle_toi (param $x i32) (param $y i32) (param $dx i32) (param $dy i32) (param $cx i32) (param $cy i32) (param $r i32) (result i32)
    (local $a i64) (local $rr i64) (local $dot i64) (local $near i32) (local $lo i32) (local $hi i32) (local $mid i32)
    (local.set $x (i32.sub (local.get $x) (local.get $cx)))
    (local.set $y (i32.sub (local.get $y) (local.get $cy)))
    ;; This bound also guarantees dot * 65536 fits i64 at capped speeds.
    (if (i32.or (i32.gt_u (call $abs (local.get $x)) (i32.add (call $abs (local.get $dx)) (local.get $r)))
      (i32.gt_u (call $abs (local.get $y)) (i32.add (call $abs (local.get $dy)) (local.get $r)))) (then (return (i32.const 65537))))
    (local.set $rr (call $dist2 (local.get $r) (i32.const 0)))
    (if (i64.le_s (call $dist2 (local.get $x) (local.get $y)) (local.get $rr)) (then (return (i32.const 0))))
    (local.set $a (call $dist2 (local.get $dx) (local.get $dy)))
    (if (i64.eqz (local.get $a)) (then (return (i32.const 65537))))
    (local.set $dot (i64.add (i64.mul (i64.extend_i32_s (local.get $x)) (i64.extend_i32_s (local.get $dx)))
      (i64.mul (i64.extend_i32_s (local.get $y)) (i64.extend_i32_s (local.get $dy)))))
    (if (i64.ge_s (local.get $dot) (i64.const 0)) (then (return (i32.const 65537))))
    (local.set $near (if (result i32) (i64.ge_s (i64.sub (i64.const 0) (local.get $dot)) (local.get $a)) (then (i32.const 65536)) (else (i32.wrap_i64 (i64.div_s (i64.mul (i64.sub (i64.const 0) (local.get $dot)) (i64.const 65536)) (local.get $a))))))
    (local.set $near (call $min (local.get $near) (i32.const 65536)))
    (if (i64.gt_s (call $circle_dist (local.get $x) (local.get $y) (local.get $dx) (local.get $dy) (local.get $near)) (local.get $rr))
      (then (return (i32.const 65537))))
    (local.set $hi (local.get $near))
    (block $found (loop $bisect
      (br_if $found (i32.le_s (i32.sub (local.get $hi) (local.get $lo)) (i32.const 1)))
      (local.set $mid (i32.div_u (i32.add (local.get $hi) (local.get $lo)) (i32.const 2)))
      (if (i64.le_s (call $circle_dist (local.get $x) (local.get $y) (local.get $dx) (local.get $dy) (local.get $mid)) (local.get $rr))
        (then (local.set $hi (local.get $mid))) (else (local.set $lo (local.get $mid))))
      (br $bisect))) (local.get $hi))
  (func $face_toi (param $x i32) (param $y i32) (param $dx i32) (param $dy i32) (param $plane i32) (param $low i32) (param $high i32) (result i32)
    (local $t64 i64) (local $t i32) (local $at i32)
    (if (i32.eqz (local.get $dx)) (then (return (i32.const 65537))))
    (local.set $t64 (i64.div_s (i64.mul (i64.extend_i32_s (i32.sub (local.get $plane) (local.get $x))) (i64.const 65536)) (i64.extend_i32_s (local.get $dx))))
    (if (i32.or (i64.lt_s (local.get $t64) (i64.const 0)) (i64.gt_s (local.get $t64) (i64.const 65536))) (then (return (i32.const 65537))))
    (local.set $t (i32.wrap_i64 (local.get $t64)))
    (local.set $at (i32.add (local.get $y) (call $mul (local.get $dy) (local.get $t))))
    (if (i32.or (i32.lt_s (local.get $at) (local.get $low)) (i32.gt_s (local.get $at) (local.get $high))) (then (return (i32.const 65537))))
    (local.get $t))
  (func $rect_toi (param $x i32) (param $y i32) (param $dx i32) (param $dy i32) (param $rect i32) (param $r i32) (result i32)
    (local $left i32) (local $top i32) (local $right i32) (local $bottom i32) (local $t i32)
    (local.set $left (i32.load (local.get $rect))) (local.set $top (i32.load offset=4 (local.get $rect)))
    (local.set $right (i32.load offset=8 (local.get $rect))) (local.set $bottom (i32.load offset=12 (local.get $rect)))
    (if (i64.le_s (call $dist2
      (i32.sub (local.get $x) (call $max (local.get $left) (call $min (local.get $x) (local.get $right))))
      (i32.sub (local.get $y) (call $max (local.get $top) (call $min (local.get $y) (local.get $bottom)))))
      (call $dist2 (local.get $r) (i32.const 0))) (then (return (i32.const 0))))
    (local.set $t (i32.const 65537))
    (if (i32.gt_s (local.get $dx) (i32.const 0)) (then (local.set $t (call $min (local.get $t) (call $face_toi (local.get $x) (local.get $y) (local.get $dx) (local.get $dy) (i32.sub (local.get $left) (local.get $r)) (local.get $top) (local.get $bottom))))))
    (if (i32.lt_s (local.get $dx) (i32.const 0)) (then (local.set $t (call $min (local.get $t) (call $face_toi (local.get $x) (local.get $y) (local.get $dx) (local.get $dy) (i32.add (local.get $right) (local.get $r)) (local.get $top) (local.get $bottom))))))
    (if (i32.gt_s (local.get $dy) (i32.const 0)) (then (local.set $t (call $min (local.get $t) (call $face_toi (local.get $y) (local.get $x) (local.get $dy) (local.get $dx) (i32.sub (local.get $top) (local.get $r)) (local.get $left) (local.get $right))))))
    (if (i32.lt_s (local.get $dy) (i32.const 0)) (then (local.set $t (call $min (local.get $t) (call $face_toi (local.get $y) (local.get $x) (local.get $dy) (local.get $dx) (i32.add (local.get $bottom) (local.get $r)) (local.get $left) (local.get $right))))))
    (local.set $t (call $min (local.get $t) (call $circle_toi (local.get $x) (local.get $y) (local.get $dx) (local.get $dy) (local.get $left) (local.get $top) (local.get $r))))
    (local.set $t (call $min (local.get $t) (call $circle_toi (local.get $x) (local.get $y) (local.get $dx) (local.get $dy) (local.get $right) (local.get $top) (local.get $r))))
    (local.set $t (call $min (local.get $t) (call $circle_toi (local.get $x) (local.get $y) (local.get $dx) (local.get $dy) (local.get $left) (local.get $bottom) (local.get $r))))
    (call $min (local.get $t) (call $circle_toi (local.get $x) (local.get $y) (local.get $dx) (local.get $dy) (local.get $right) (local.get $bottom) (local.get $r))))
  ;; Query the swept AABB's grid cells, OR their solid bitsets, then visit stable IDs.
  (func $terrain_toi (param $x i32) (param $y i32) (param $dx i32) (param $dy i32) (param $r i32) (result i32)
    (local $x0 i32) (local $x1 i32) (local $y0 i32) (local $y1 i32) (local $gx i32) (local $gy i32) (local $mask i32) (local $id i32) (local $t i32)
    (local.set $x0 (call $max (i32.const 0) (i32.div_s (i32.sub (call $min (local.get $x) (i32.add (local.get $x) (local.get $dx))) (local.get $r)) (i32.const 26214400))))
    (local.set $x1 (call $min (i32.const 15) (i32.div_s (i32.add (call $max (local.get $x) (i32.add (local.get $x) (local.get $dx))) (local.get $r)) (i32.const 26214400))))
    (local.set $y0 (call $max (i32.const 0) (i32.div_s (i32.sub (call $min (local.get $y) (i32.add (local.get $y) (local.get $dy))) (local.get $r)) (i32.const 26214400))))
    (local.set $y1 (call $min (i32.const 9) (i32.div_s (i32.add (call $max (local.get $y) (i32.add (local.get $y) (local.get $dy))) (local.get $r)) (i32.const 26214400))))
    (local.set $gy (local.get $y0))
    (block $rows_done (loop $rows
      (br_if $rows_done (i32.gt_s (local.get $gy) (local.get $y1)))
      (local.set $gx (local.get $x0))
      (block $cols_done (loop $cols
        (br_if $cols_done (i32.gt_s (local.get $gx) (local.get $x1)))
        (local.set $mask (i32.or (local.get $mask) (i32.load (i32.add (i32.const 33792) (i32.mul (i32.add (i32.mul (local.get $gy) (i32.const 16)) (local.get $gx)) (i32.const 4))))))
        (local.set $gx (i32.add (local.get $gx) (i32.const 1))) (br $cols)))
      (local.set $gy (i32.add (local.get $gy) (i32.const 1))) (br $rows)))
    (local.set $t (i32.const 65537))
    (loop $solids
      (if (i32.and (local.get $mask) (i32.shl (i32.const 1) (local.get $id))) (then
        (local.set $t (call $min (local.get $t) (call $rect_toi (local.get $x) (local.get $y) (local.get $dx) (local.get $dy)
          (i32.add (i32.const 32832) (i32.mul (local.get $id) (i32.const 16))) (local.get $r))))))
      (local.set $id (i32.add (local.get $id) (i32.const 1)))
      (br_if $solids (i32.lt_u (local.get $id) (call $solid_count)))) (local.get $t))
