  ;; Cosmetic scratch only. At most 512 events per tick; IDs are tick/entity/index.
  ;; Record: tick, entity, index, type, x, y, player, data (8 i32 words).
  (func $event (param $type i32) (param $entity i32) (param $x i32) (param $y i32) (param $player i32) (param $data i32)
    (local $count i32) (local $dst i32)
    (local.set $count (i32.load (i32.const 131072)))
    (if (i32.ge_u (local.get $count) (i32.const 512)) (then (return)))
    (local.set $dst (i32.add (i32.const 131076) (i32.mul (local.get $count) (i32.const 32))))
    (i32.store (local.get $dst) (i32.load (i32.const 4096)))
    (i32.store offset=4 (local.get $dst) (local.get $entity))
    (i32.store offset=8 (local.get $dst) (local.get $count))
    (i32.store offset=12 (local.get $dst) (local.get $type))
    (i32.store offset=16 (local.get $dst) (local.get $x))
    (i32.store offset=20 (local.get $dst) (local.get $y))
    (i32.store offset=24 (local.get $dst) (local.get $player))
    (i32.store offset=28 (local.get $dst) (local.get $data))
    (i32.store (i32.const 131072) (i32.add (local.get $count) (i32.const 1))))
  (func $ship_event (param $type i32) (param $p i32) (param $data i32)
    (local $id i32)
    (local.set $id (i32.div_u (i32.sub (local.get $p) (i32.const 4160)) (i32.const 64)))
    (call $event (local.get $type) (local.get $id) (i32.load (local.get $p)) (i32.load offset=4 (local.get $p)) (local.get $id) (local.get $data)))
